apiVersion: v1
kind: Service
metadata:
  name: ganymede-nginx-service
spec:
  selector:
    app: ganymede
    deployment: ganymede-nginx
  ports:
    - name: ganymede-nginx-http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
