apiVersion: v1
kind: Service
metadata:
  name: ganymede-nginx-service
spec:
  selector:
    matchFields:
      - metadata.name: ganymede-nginx-deployment
  ports:
    - name: ganymede-nginx-http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
