apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

configMapGenerator:
  - behavior: merge
    name: argocd-cmd-params-cm
    literals:
      - "server.insecure=true"
  - behavior: merge
    name: argocd-cm
    literals:
      - kustomize.buildOptions=--enable-helm

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.0/manifests/install.yaml
  - ingress.yml

patchesStrategicMerge:
  - patch.yml
