apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellyfin

commonLabels:
  app: jellyfin

configMapGenerator:
  - name: jellyfin-config
    files:
      - config.yml

bases:
  - ./base
