apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB4jNNOV0s/HlHDF8dRi6hzFyblTo9TS87T0StgIhYKhj2B903GVvt/QSNVH0UQkDf4qwrPJnAFYlEu4VDWg77B7oaU2blsVlCnGwuT93aQ964M08ZAqdaz6P72sPOdYwvYOJFjMBsIKoJBvshlDoHl/WOBE8J2ExgR6PcJ6EyMY+s8MTiQ6XIIzI2eh2zKOqC0MbP3469BN5iBLJ+fFGDE1mtNow/g3C8DgRtkhDBEFmZUIpR7u8PfJSK9fG4UkwJZF32WJCKCJyreUSTiqcKL2W6YzGnbbOdOnr7A3gUL1xCmULESBrgFwssjhL2bGH6ndfJqh4zJVjcuhgLJzdatE0rJlbtoVHQUQrHmjZ5uG7fCMODQQgMmjkTeBSGZNPb53Tj+pg9yMcKz0HbAqj1eqAmgEY/uOBvXKHjfMwUnJHo4+jwgz5oq5z86JD/oFBSVtOgqw5URmUbaDDDBTZ5cmyttM96I5V4vAsLTmsFD9aYhp9LSCrivDankkvJgdr6ICUI2csRyzymZS4OJsiuAHZEFht+b0cDgX/G9a4RviLCcCZRoWLfN6NaAnKrFhIrL81F6iioLLW4fyrgMhkLcDFV7g6DBoiWEmf68Xx0Q8DoHtYZ/27Kj1CQ8bzPRLZ6wPQrH4143KcA8mHpwC69RWRzf+uATYePkcp0PWOBOetyZgsG17V6tHw/bQbsAdyx4WUn89nk8lKXE85qQMdVmVxa5sv1ZZ8zZB9JkX52BR8vEEnpCpxCk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque

