apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-deployment.yml
  - db-deployment.yml
  - frontend-deployment.yml
  - nginx-deployment.yml
  - service.yml
  - ingress.yml
  - pv.yml
  - pvc.yml
  - configmap.yml
  - api-sealed-secret.yml
  - db-sealed-secret.yml
