apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yml
  - pvc.yml
  - ingress.yml
  - ./frontend/deployment.yml
  - ./frontend/service.yml
  - ./database/deployment.yml
  - ./database/service.yml
  - ./database/sealed-secret.yml
  - ./api/deployment.yml
  - ./api/service.yml
  - ./api/sealed-secret.yml
  - ./nginx/deployment.yml
  - ./nginx/service.yml
  - ./nginx/configmap.yml
