apiVersion: v1
kind: PersistentVolume
metadata:
  name: ganymede-videos-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  nfs:
    server: 197.100.1.230
    path: /mnt/user/test-k3s/media/vods
  storageClassName: nfs
