apiVersion: v1
kind: Service
metadata:
  name: ganymede
  labels:
    app: ganymede
spec:
  selector:
    app: ganymede
  ports:
    - name: ganymede-frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: ganymede-api
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: ganymede-nginx
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: ganymede-database
      port: 5432
      targetPort: 5432
      protocol: TCP
