apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganymede-api
  labels:
    app: ganymede-api
    deployment: ganymede-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganymede-api
      deployment: ganymede-api
  template:
    metadata:
      labels:
        app: ganymede-api
        deployment: ganymede-api
    spec:
      containers:
        - name: ganymede-api
          image: ghcr.io/zibbp/ganymede:main@sha256:81f657b45c605871405f65d79d6a6fa7797ba2d5d2cd15ce6dae1b35300459be
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ganymede-api-config
            - secretRef:
                name: ganymede-api-secret
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /logs
            - name: videos-nfs
              mountPath: /vods
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ganymede-data-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: ganymede-logs-pvc
        - name: videos-nfs
          persistentVolumeClaim:
            claimName: ganymede-videos-nfs-pv
