apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganymede-api-deployment
  labels:
    app: ganymede-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganymede-api
  template:
    metadata:
      labels:
        app: ganymede-api
    spec:
      containers:
        - name: ganymede-api
          image: ghcr.io/zibbp/ganymede:main@sha256:d9d43b4e76df83e03e7fda6a1cf472c75be51dd6946beb18b37518de02e94c7f
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ganymede-api-config
            - secretRef:
                name: ganymede-api-secret
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /logs
            - name: videos-nfs
              mountPath: /vods
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ganymede-data-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: ganymede-logs-pvc
        - name: videos-nfs
          persistentVolumeClaim:
            claimName: ganymede-videos-nfs-pv
