apiVersion: v1
kind: Service
metadata:
  name: ganymede-api-service
spec:
  selector:
    deployment: ganymede-api
  ports:
    - name: ganymede-api-http
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
