apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ganymede

commonLabels:
  app: ganymede

configMapGenerator:
  - name: ganymede-frontend-config
    literals:
      - API_URL=https://api-ganymede.lab.zibbp.net
      - CDN_URL=https://cdn-ganymede.lab.zibbp.net
      - SHOW_SSO_LOGIN_BUTTON=true
      - FORCE_SSO_AUTH=false
      - REQUIRE_LOGIN=false
  - name: ganymede-database-config
    literals:
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
  - name: ganymede-api-config
    literals:
      - TZ=America/Chicago
      - DB_HOST=ganymede
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - FRONTEND_HOST=https://ganymede.lab.zibbp.net
      - COOKIE_DOMAIN=ganymede.lab.zibbp.net
bases:
  - ./base
