apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ganymede

commonLabels:
  app: ganymede

configMapGenerator:
  - name: ganymede-api-config
    literals:
      - TZ=America/Chicago
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - FRONTEND_HOST=https://ganymede.lab.zibbp.net
  - name: ganymede-frontend-config
    files:
      - frontend-config.yml
  - name: ganymede-db-config
    files:
      - db-config.yml
bases:
  - ./base
