apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yml

helmCharts:
  - name: prometheus
    releaseName: prometheus-community
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    valuesFile: values.yml
    version: 19.6.0
