apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCnHulXIkNbWWKiN4TwkAnoq0WG0UoYllxWifEJKinmZ4COYnweow/nL+gf3nxMuXoPDo1lNI96DnaB5rJ+eWfIv/LSrzTkelojBa4cTy4KNGLQySkEODgw0/STbrlQBFgRN+zN7CFjvsvmSWiL8vNZdzvHgmeOAgF9g7C/SeVauyY9dipWPC0MwfORC4qbbHoD9wx4Fyv8BK0rCx2yI5q7EAlXWmNa1dQpqHCYyZG9yQwT7RIsgjpAJdLJTlgPzO4YgIGFDnOOjIPydJdq9In6IZvr3X1kVX+ATv1N2GAxBTESZDJ7gfvaFlI2a0V0j9wRnxOEqT0XF0pgr/h3fENuwEU/722D/U4IoYIEFOhYhEr0ZCOhT/gNEVbDPiLUxr410EY85glzaASjwsB/0ItgkdzUbwbZBjULCOB3Ez8EasF6htirxCR6NU/EKX38P10B4wenx/RJBk1pcnKXnNClwDUZhsBP0iT9OTSy0KNvvwmG8sbK178dzvpqIrfHG3GjZueLxzGn8WTln4ao4EGPvL31PxPzMi/mPlmkbC/kjAMsxndlIiB7CLlKFSQ72eaIiQxKkmMQS2nSEA4jAR0mksG9QsDjNl4P6fNcltNIf9lSqhv+6M7gN85W2bv9esz8/fm9khSmjAS+6Gntku5nYQwbICxw7Yl6UrHhuouml+hS2p4qm9JBgH8OKCi3dEua+IXi+vfdYdzcMnE2GXw=
    admin-user: AgB3oGOq4zC8/7ApxMSTUQOompnL9QZWyIrf3BAcm+aNvMAbKHmMq9ZwCtZpBBSu+pYbUj5DLwV1gqLVeMEPKscWHfEJaMiL2k/Qg04NA4MIKV5FLoAz2pON/VTuMB1+dps1uPOLtbkTBxtwDv8JST0YxtPFwpahCVKBCUIL1fXnxjkg0j7tqD0Q7/mCPIGi6Rl5ovkDkXO5WdQPHM9lNaYI19Kr8MO5NBfmKFA6kJuvusXKTDdFd088EPnAGf1GtqolnnP7pCHU6LGs6Ee+3QyIWJJMNoP42vZ5tktTZvI4R/vyspa2NF9XHuejrc4UcNcSXnd4dGVKyL0EM41jfbaLaqrZIC8HQECyeRtXE3TSTjmvyVY0cM9ePHUzpvgZEYvlIPKA9umwz1148hPR9tyztrzGX1yZRprS+QFq91NcTjkhtdqFmKzNHSdibwuPGFkOpPFryS4Nd0SPPVKeypUnkkoOHmcCqDAw8MwWjrAn6JBpNyl7A1y6M31+Wrl9lQtNiUIUBYdsTyo65Z9rW+uB/DUDrUyyISA3WUjU1Tft1b+KZ8rFVw4QHnFMd1+vjuDghM4DpjOCTrYF7tQ0ULmRm8D//s6d72Vhpdl5hun2g/msPFqYiKHMCNI+pQ16zSjfzilrsFy7CsWCDqu7mRr14UY3umiF0hEZ4KWkzICKbjCfFerBXDUB6P3+X92R39PzRFPZvA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

