---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-zibbp-net
  namespace: default
spec:
  secretName: lab-zibbp-net-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.lab.zibbp.net"
  dnsNames:
    - "lab.zibbp.net"
    - "*.lab.zibbp.net"
