apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ganymede-database-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAgqBPw86mLdBkbXcyGMpv1dQJHs/NQiRROzupU5JDtp2CXoAHdC8E6T5o49C6dxZTd2GGaTkkU39xXIrRxMhBrdPiL2geSe2GcvmlENE5sOvE0q1Gi6aobdlAC8K2BdcAHkW2gu43zLtoENLO8z2hk2LVF8cGYxRtRtnNbaCQf6sHjwy+JBlDxFOcLYTEwrctTZoMAR3b5+ewCOqpBs58uFkAN+OTqWB/APyW6GtPU/w/OmDkubP/EdXvkiIQeOfwWRyQDqJx+zgstW4w4AIF6fXqxzYXNSXhaQidgR8mN+2VWOz8tWjnsSggDkOi3r2D+wGET7j8r4Fb3HTZMTd04lQueIdQrh6bDFgGqwEgI3VVIwz1cqRezdhQ9qmPcb1+yUqwME42tCNb67NC/pOpA0AQHP4KpQntFq7M36y1ESXhtDegjlIn9PRtGT2GC2bjoMvPk8VQ033NUU0nYha7K73fl/m6SVY69UoRf7McwNvn+VWgV5PyWnGh1IMKZr3/5qQbGqs929vpbv0G/8Ep8IMk8Kmr3VxWNTC5tq8wQ2ETVeLHbbP1ovfEgZfSO9wPvPM515kX5gf0lE042DXUGmqZXOsQ1twbEtamUd/mqQATiOS4FAegLApr8IH6DTLKBIPF2agbJ0UYYRtdBQrindeqs0lgKG9O+WCftRpuFRf+0P/Fkgqgl/d9Qw7PyQivsQgq6O4YANLaKe2bSjXw4MQrQVuom9fhCmFjGLM6Jeu5K2HCL8RdpgD2eweYLctQ=
  template:
    metadata:
      creationTimestamp: null
      name: ganymede-database-secret
      namespace: default
    type: Opaque
