apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ganymede-database-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB7e7fqcrXkkQ358VuE5ESkg6oDifqkFFqWHqZB6+tGHfYFzue/jZS+FvGrtLwBwRY7QdjDYXrpdOKkZ4wz+lfdLC8tQM37MxXSFaUXOsPhWpIgvW/ECljwP/mtPT/ScBx16AEsLJKPdQQ9WekAI61Re0Czou9msLaJDJrzR0OE/87546t2wWqxlEBioocZ5f1TQ+BQ1HeInnmOVUFxO7OLe4GTWvsUnsVfBvDdKtRDS9FuAxFCZHk7TUpW2spezi6Z47PesSYOP4AAp1z9xCdcN1JhB8sixl5ghY+cjPUtuyMyPoRU8PuDEN44pOk4/iSk1o+lQRszxTo1Rwxy6ENBbjS+Re3pvjJ2sTLyerRUUNZNoDmX4cpJAnICxdVnoXtIC+DQ+OCm9Ibsqc903dSHC67aEs7axDSS9o6rqgUBhKDRCF4ghMWLFrscUGNEtzGQ5r0oVkUlEhdmweeNxYRvnzzr7qiHMFsbzGGtFLGc0V9Sc9u1Em/889fcmx+9tWnSzNS7liPAkHrcGYCxCd9KXK8mudkVFH5IswToi3hPB5FYeyW1q+cbDbS5LB4cd8/tKPOLpsjgoVYiQB1iv/vpRqzZILOUYRClrUpyoxP0ef/oRFDlIowx+MgfydX/KEYSmn8qygjdvxPggYBeEzEXJ/J/ZTT/dudwFO4sQvmg16eX29nG3Wc24NohlY7cOctpB8xw5QJ23zKpF7f4XTKWqMHfV1QVFQJGwxMPiABv+squP3iuTbWiPNBCLmsqoUA=
  template:
    metadata:
      creationTimestamp: null
      name: ganymede-database-secret
      namespace: default

