apiVersion: v1
kind: Service
metadata:
  name: ganymede-database-service
spec:
  selector:
    matchFields:
      - metadata.name: ganymede-database-deployment
  ports:
    - name: ganymede-database-tcp
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
