apiVersion: v1
kind: Service
metadata:
  name: ganymede-database
  labels:
    app: ganymede-database
spec:
  selector:
    app: ganymede-database
  ports:
    - name: ganymede-database
      port: 5432
      targetPort: 5432
      protocol: TCP
