apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganymede-frontend
  labels:
    app: ganymede-frontend
    deployment: ganymede-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganymede-frontend
      deployment: ganymede-frontend
  template:
    metadata:
      labels:
        app: ganymede-frontend
        deployment: ganymede-frontend
    spec:
      containers:
        - name: ganymede-frontend
          image: ghcr.io/zibbp/ganymede-frontend:main@sha256:c34fa01ab764eae73ba69ec0decf318b32272ca8ab91164dde42fcf3cf89f454
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ganymede-frontend-config
          ports:
            - containerPort: 3000
