apiVersion: v1
kind: Service
metadata:
  name: ganymede-frontend-service
spec:
  selector:
    matchFields:
      - metadata.name: ganymede-frontend-deployment
  ports:
    - name: ganymede-frontend-http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
