apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:4.3.2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: radarr-config
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: movies-nfs
          nfs:
            server: 197.100.1.230
            path: /mnt/user/test-k3s/media/movies
