apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  capacity:
    storage: 1Ti
  nfs:
    path: /mnt/user/test-k3s/media/movies
    server: 197.100.1.230
