apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  annotations:
    longhorn.io/replica-count: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
