apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-tycho
  resources:
    requests:
      storage: 1Gi
