apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  annotations: io.longhorn.auto-trim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-tycho
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-pvc
  annotations: io.longhorn.auto-trim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-tycho
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-incomplete-pvc
  annotations: io.longhorn.auto-trim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-tycho
  resources:
    requests:
      storage: 100Gi
