apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync-system
  namespace: argocd
  annotations:
    helm.sh/hook: crd-install
spec:
  project: default
  source:
    chart: volsync
    repoURL: https://backube.github.io/helm-charts
    targetRevision: 0.5.0
    helm:
      releaseName: volsync-system
      createNamespace: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: volsync-system
