apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
spec:
  project: default
  source:
    chart: volsync
    repoURL: https://backube.github.io/helm-charts
    targetRevision: 0.5.0
    helm:
      releaseName: volsync
  destination:
    server: "https://kubernetes.default.svc"
    namespace: volsync
